# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network :private_network, ip: "192.168.33.33"
  # config.vm.network :forwarded_port, host: 3000, guest: 3000
  # config.vm.network :forwarded_port, host: 8080, guest: 8080
  config.vm.synced_folder "/var/www", "/var/www",
                          create: true, owner: "vagrant", group: "vagrant"

  # necessary package
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update -y && sudo apt-get upgrade -y
    sudo apt-get install -y make gcc wget zsh curl \
                            libssl-dev \
                            libcurl4-openssl-dev \
                            libexpat1-dev \
                            autoconf \
                            build-essential \
                            gettext \
                            tig \
                            vim
  SHELL

  config.vm.provision :itamae do |i|
    i.sudo = true
    i.recipes = ["./recipe.rb"]
  end
end

