# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "nixos/nixos-16.09-x86_64"
  config.vm.network :forwarded_port, host: 2300, guest: 2300
  config.vm.network :forwarded_port, host: 3000, guest: 3000
  config.vm.network :forwarded_port, host: 8080, guest: 8080
  config.vm.network :forwarded_port, host: 4000, guest: 4000
  config.vm.network :forwarded_port, host: 4567, guest: 4567
  config.vm.network :private_network, ip: "192.168.33.30"
  # config.vm.box_check_update = false
  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |v|
    v.memory = 3072
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
  SHELL
end
